set shell := ["powershell.exe", "-c"]
install :
    @echo "Building the project..."
    pip install -r requirements.txt
optimize-model:
    @echo "Optimizing the model..."
    python export_model.py
run-app:
    @echo "Running the application..."
    python run.py


    
