set shell := ["powershell.exe", "-c"]
install :
    @echo "Building the project..."
    pip install -r requirements.txt
install-model:
    @echo "Installing the model..."
    python -c "from ultralytics import YOLO; YOLO('weights/yolov8m.pt', task='detect')"
optimize-model:
    @echo "Optimizing the model..."
    python export_model.py

run-app:
    @echo "Running the application..."
    python run.py


    
